lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 86400 # durée de vie du token en secondes
  token_extractors:
    cookie:
      name: BEARER
  set_cookies:
    BEARER:
      lifetime: 86400 # durée de vie du cookie en secondes
      path: /
      domain: null
      secure: true
      httpOnly: true
      samesite: lax
