lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    set_cookies:
        BEARER:
            lifetime: 3600 # durée de vie du cookie en secondes
            path: /
            domain: null
            secure: true
            httpOnly: true
            samesite: lax
